class Comments {
  final int id;
  final String postId;
  final String username;
  final String content;
  final String imageUrl;
  int likes;
  bool isLiked;
  final bool isVerified;
  final String date;
  final bool hasStory;

  void toggleLike() {
    isLiked = !isLiked;
    likes += isLiked ? 1 : -1;
  }

  Comments({
    required this.id,
    required this.postId,
    required this.username,
    required this.content,
    required this.imageUrl,
    required this.likes,
    required this.isLiked,
    required this.isVerified,
    required this.date,
    required this.hasStory,
  });
}

List<Comments> commentDataset = [
  Comments(
    id: 1,
    postId: "1",
    username: "alex_pro",
    content:
        "This perspective is absolutely incredible! 🔥, its really well done and i wish nothing but the best for you, you guys are really came through,This perspective is absolutely incredible! 🔥, its really well done and i wish nothing but the best for you, you guys are really came through,This perspective is absolutely incredible! 🔥, its really well done and i wish nothing but the best for you, you guys are really came through",
    imageUrl: "https://i.pravatar.cc/150?u=alex",
    likes: 42,
    isLiked: true,
    isVerified: true,
    date: "2h",
    hasStory: true,
  ),
  Comments(
    id: 2,
    postId: "1",
    username: "sara_design",
    content: "The color palette here is so soothing.",
    imageUrl: "https://i.pravatar.cc/150?u=sara",
    likes: 15,
    isLiked: false,
    isVerified: false,
    date: "3h",
    hasStory: false,
  ),
  Comments(
    id: 3,
    postId: "1",
    username: "dev_mike",
    content: "Wait, was this shot on a Mirrorless or DSLR?",
    imageUrl: "https://i.pravatar.cc/150?u=mike",
    likes: 0,
    isLiked: false,
    isVerified: true,
    date: "5h",
    hasStory: true,
  ),
  Comments(
    id: 4,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 5,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 6,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 7,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 8,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 9,
    postId: "1",
    username: "pixel_pioneer",
    content: "Composition goals right here. 🙌",
    imageUrl: "https://i.pravatar.cc/150?u=pixel",
    likes: 112,
    isLiked: true,
    isVerified: false,
    date: "6h",
    hasStory: false,
  ),
  Comments(
    id: 9,
    postId: "1",
    username: "wanderlust_er",
    content: "Adding this to my bucket list immediately!",
    imageUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150",
    likes: 150,
    isLiked: true,
    isVerified: true,
    date: "1h",
    hasStory: true,
  ),
  Comments(
    id: 10,
    postId: "1",
    username: "coffee_addict",
    content: "Is there a good cafe nearby?",
    imageUrl: "https://i.pravatar.cc/150?u=coffee",
    likes: 8,
    isLiked: false,
    isVerified: false,
    date: "2h",
    hasStory: false,
  ),
  Comments(
    id: 11,
    postId: "1",
    username: "gamer_zane",
    content: "The frame rate on this clip is buttery smooth.",
    imageUrl: "https://i.pravatar.cc/150?u=zane",
    likes: 204,
    isLiked: true,
    isVerified: true,
    date: "10m",
    hasStory: true,
  ),
  Comments(
    id: 12,
    postId: "1",
    username: "neon_vibes",
    content: "Love the aesthetic you're going for.",
    imageUrl: "https://i.pravatar.cc/150?u=neon",
    likes: 15,
    isLiked: false,
    isVerified: false,
    date: "30m",
    hasStory: false,
  ),
  Comments(
    id: 13,
    postId: "1",
    username: "zen_master",
    content: "Take a deep breath and enjoy the view.",
    imageUrl: "https://i.pravatar.cc/150?u=zen",
    likes: 142,
    isLiked: true,
    isVerified: true,
    date: "7h",
    hasStory: true,
  ),

  // --- POST 2 ---
  Comments(
    id: 13,
    postId: "2",
    username: "wanderlust_er",
    content: "Adding this to my bucket list immediately!",
    imageUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150",
    likes: 150,
    isLiked: true,
    isVerified: true,
    date: "1h",
    hasStory: true,
  ),
  Comments(
    id: 14,
    postId: "2",
    username: "coffee_addict",
    content: "Is there a good cafe nearby?",
    imageUrl: "https://i.pravatar.cc/150?u=coffee",
    likes: 8,
    isLiked: false,
    isVerified: false,
    date: "2h",
    hasStory: false,
  ),

  // --- POST 4 (Selection of comments) ---
  Comments(
    id: 17,
    postId: "4",
    username: "gamer_zane",
    content: "The frame rate on this clip is buttery smooth.",
    imageUrl: "https://i.pravatar.cc/150?u=zane",
    likes: 204,
    isLiked: true,
    isVerified: true,
    date: "10m",
    hasStory: true,
  ),
  Comments(
    id: 18,
    postId: "4",
    username: "neon_vibes",
    content: "Love the aesthetic you're going for.",
    imageUrl: "https://i.pravatar.cc/150?u=neon",
    likes: 15,
    isLiked: false,
    isVerified: false,
    date: "30m",
    hasStory: false,
  ),
  Comments(
    id: 25,
    postId: "4",
    username: "zen_master",
    content: "Take a deep breath and enjoy the view.",
    imageUrl: "https://i.pravatar.cc/150?u=zen",
    likes: 142,
    isLiked: true,
    isVerified: true,
    date: "7h",
    hasStory: true,
  ),

  // --- POST 6 TO 10 ---
  Comments(
    id: 37,
    postId: "6",
    username: "yogini",
    content: "Consistency is key! Great job today.",
    imageUrl: "https://i.pravatar.cc/150?u=yoga",
    likes: 120,
    isLiked: true,
    isVerified: true,
    date: "3h",
    hasStory: true,
  ),
  Comments(
    id: 39,
    postId: "8",
    username: "cat_lover",
    content: "The cuteness is actually overwhelming. 🐈",
    imageUrl: "https://i.pravatar.cc/150?u=cat",
    likes: 800,
    isLiked: true,
    isVerified: false,
    date: "1d",
    hasStory: true,
  ),
  Comments(
    id: 41,
    postId: "10",
    username: "pizza_king",
    content: "Extra cheese or we riot. 🍕",
    imageUrl: "https://i.pravatar.cc/150?u=pizza",
    likes: 45,
    isLiked: true,
    isVerified: false,
    date: "5m",
    hasStory: true,
  ),
];

List<Comments> filterCommentsByPostId(String postId) {
  List<Comments> filteredComments = commentDataset.where((comment) => comment.postId == postId).toList();
  return filteredComments;
}

int getTotalCommentsForPost(String postId) {
  return filterCommentsByPostId(postId).length;
}
